# Documentation
nelmio_api_doc:
    name:                 'API DEMO'
    exclude_sections:     []
    default_sections_opened:  true
    cache:
        enabled:              true
        file:                 '%kernel.cache_dir%/api-doc.cache'
    sandbox:
            authentication:             # default is `~` (`null`), if set, the sandbox automatically
                                        # send authenticated requests using the configured `delivery`

                name: Authorization      # access token name or query parameter name or header name

                delivery: http          # `query`, `http`, and `header` are supported

                # Required if http delivery is selected.
                type:     bearer         # `basic`, `bearer` are supported

                custom_endpoint: false   # default is `false`, if `true`, your user will be able to
                                        # specify its own endpoint

            enabled:  true              # default is `true`, you can set this parameter to `false`
                                        # to disable the sandbox
                                        # to define which URL to call through the sandbox

            accept_type: application/json           # default is `~` (`null`), if set, the value is
