fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: api
    user_class: AppBundle\Entity\User
    from_email:
        address: "diego.grassato@gmail.com"
        sender_name: "blablabla"