fos_oauth_server:
    db_driver: orm
    client_class:        AppBundle\Entity\Oauth2\Client
    access_token_class:  AppBundle\Entity\Oauth2\AccessToken
    refresh_token_class: AppBundle\Entity\Oauth2\RefreshToken
    auth_code_class:     AppBundle\Entity\Oauth2\AuthCode
    service:
        user_provider: platform.user.provider
        options:
            supported_scopes: user celular android ios
            # Changing tokens and authcode lifetime
            access_token_lifetime: 3600000
            #refresh_token_lifetime: 1209600
            #auth_code_lifetime: 30
