app_v1:
    resource: "@AppBundle/Rest/V1"
    type: rest
    prefix: /api/{version}/{locale}
    condition: "request.attributes.get('version') == 'v1'"
    defaults:
        locale: en
        format: json
        version: v1
    requirements:
        format: "json|xml"
        locale: "%locale_supported%"

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

jwt_server_token:
    resource: "@BaseBundle/Resources/config/routing/token.xml"
    prefix: /api/
