app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api/%api_version%/{_locale}
    defaults:
        _locale: en
        _format: json
    requirements:
        _format: "json|xml"
        _locale: "%locale_supported%"

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

jwt_server_token:
    resource: "@BaseBundle/Resources/config/routing/token.xml"
    prefix: /api/
