parameters:
    platform.entity.user.class: AppBundle\Entity\User
    platform.user.provider.class: AppBundle\Provider\UserProvider
services:
#    app.manager:
#      class: AppBundle\Manager\AppManager
#      calls:
#        - [setEventDispatcher, ["@event_dispatcher"]]
#        - [setLogger, ["@logger"]]
#      arguments:
#        - '@doctrine.orm.entity_manager'
#      tags:
#          - { name: monolog.logger, channel: leads }
#    product.manager:
#      class: AppBundle\Manager\ProductManager
#      arguments:
#        - '@doctrine.orm.entity_manager'
#    category.manager:
#      class: AppBundle\Manager\CategoryManager
#      arguments:
#        - '@doctrine.orm.entity_manager'


    platform.user.provider:
        class: %platform.user.provider.class%
        arguments: ['@doctrine.orm.entity_manager']

    # Fix return access token with entity User
    fos_oauth_server.server:
        class: BaseBundle\Security\Authentication\OAuth2Ciandt
        arguments: ['@fos_oauth_server.storage', %fos_oauth_server.server.options%]

